apiVersion: v2
name: shield
description: A Helm chart for deploying Shield on Kubernetes
type: application
version: 0.1.0
appVersion: "v0.1.0"
home: https://github.com/odpf/shield
sources:
  - https://github.com/odpf/shield
  - https://github.com/odpf/charts
