apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shield.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | trim | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretConfig -}}
    {{- (print $key ": " ($val | toString | b64enc | quote )) | nindent 2 -}}
  {{- end }}
